# Generated by Django 3.2.7 on 2021-09-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210913_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='dues',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dues',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dues',
            name='month',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
