# Generated by Django 3.1.9 on 2021-10-24 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210913_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Months',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='dues',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.months'),
        ),
    ]
