# Generated by Django 3.1.9 on 2021-10-24 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211025_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Months',
            new_name='Month',
        ),
        migrations.AddField(
            model_name='dues',
            name='year',
            field=models.ForeignKey(default=2021, on_delete=django.db.models.deletion.CASCADE, to='accounts.year'),
            preserve_default=False,
        ),
    ]
