# Generated by Django 3.1.9 on 2021-10-30 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_month_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Registered Member', 'verbose_name_plural': 'Registered Members'},
        ),
        migrations.AlterModelOptions(
            name='dues',
            options={'verbose_name': 'Due', 'verbose_name_plural': 'Dues'},
        ),
        migrations.AddField(
            model_name='account',
            name='profile_pic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dues',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.month'),
        ),
        migrations.AlterField(
            model_name='dues',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.year'),
        ),
    ]
