# Generated by Django 3.1.9 on 2021-10-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20211030_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lga',
            options={'verbose_name': 'Local Govt. Area', 'verbose_name_plural': 'Local Govt. Areas'},
        ),
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
