# Generated by Django 3.1.9 on 2021-11-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20211030_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='marital_status',
            field=models.CharField(choices=[('Single(Never Married)', 'Single(Never Married)'), ('Engaged', 'Engaged'), ('Married', 'Married'), ('Seperated', 'Seperated'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=100, null=True),
        ),
    ]
