# Generated by Django 3.2.7 on 2021-11-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_account_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='reg_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
