# Generated by Django 3.2.7 on 2021-11-19 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_userprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.ForeignKey(default='Member', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.position'),
        ),
    ]
